""" 

This starter code includes two lists 
Wordlist
Descriptions

Both are the same length and can be used to make a game

Scroll to the bottom to make your own code

"""

wordlist =["Algorithm",
"Analogue",
"Analyse",
"Antivirus",
"Application",
"Arithmetic Logic Unit",
"Array",
"Artificial intelligence",
"ASCII",
"Assembly language",
"Asynchronous Transmission",
"Automatic Repeat Request (ARQ)",
"Binary",
"Biometric",
"Bit",
"Bitmap",
"BitTorrent ",
"BMP",
"Boolean",
"Bus Network",
"Byte",
"Cipher text",
"Client",
"Client side scripting ",
"Code",
"Compile",
"Computational Thinking",
"Computer",
"Computer Network",
"Control Unit",
"CPU",
"Crash",
"CSS",
"Data",
"Database",
"DBMS - Database Management System",
"Debug",
"Decompose",
"Decomposition",
"Delete",
"Denary",
"Denial of Service",
"Develop",
"Device Drivers",
"Digital",
"Download",
"Encrypt",
"Encryption",
"Enumerated",
"Even Parity Bit",
"Execute (program)",
"Field",
"File",
"Firewall",
"Float",
"FTP",
"Function",
"GIF",
"Hacking",
"Hardware",
"Header",
"Hexadecimal",
"Host",
"HTML",
"http",
"Input",
"Interface",
"Internet",
"Internet Service Provider (ISP)",
"Interrupt ",
"Interrupts",
"IP address",
"IPv6 ",
"Iteration",
"Java",
"JPEG",
"Kernel",
"LAN",
"Library Routine",
"Logic",
"Logic gate",
"Login",
"Loop",
"Lossless compression",
"Lossy compression ",
"Mac Address",
"Machine language",
"Malware ",
"Memory",
"Model",
"Monitor",
"Mouse",
"MP3",
"Multi Container Format",
"Navigate",
"Online Identity",
"OS ",
"Output",
"Packet switching ",
"Parallel processing ",
"Parity check ",
"Password",
"Peer-to-peer network",
"Pharming",
"Phishing",
"PHP ",
"Pixels",
"Plain text",
"PNG",
"Pointer ",
"POP3",
"Primary key ",
"Procedure",
"Process",
"Processor",
"Program",
"Programming language",
"Progressive Encoding",
"Protocols",
"Proxy server",
"Python",
"Query-By-Example",
"RAM ",
"Random access ",
"Record ",
"Register",
"Resolution",
"ROM",
"Router ",
"Sampling rate",
"Sampling resolution",
"Scratch",
"Scroll",
"Search",
"Secondary storage",
"Selection",
"Sequence",
"Sequence (in a program)",
"Server",
"Server side scripting ",
"SMTP",
"Software",
"Spyware",
"SSL ",
"Star Network",
"Statement",
"String",
"SVG",
"Symmetric encryption",
"Synchronous data transmission",
"System Utilities",
"Test",
"Topology",
"Torrent",
"Upload",
"User Accounts",
"User Interface",
"Validation",
"Variable",
"Vectors",
"Verification",
"Virus",
"Von Neumann",
"WAV (RIFF) file",
"Web browser",
"Zip File"]

descriptions =["a sequence of steps that describe how to solve a problem",
"Information represented by a continuously variable physical quantity",
"to work out what is meant",
"designed to detect and destroy computer viruses.",
"a program that does a specific thing",
"The part of the CPU that processes information",
"A specific type of variable that is almost like a box containing other variables. Unlike simple variable, arrays can contain multiple pieces or sets of data",
"is the intelligence exhibited by machines or software.",
"a simple way to represent letters, numbers and other characters using up to 8 binary bits",
"Assembly languages have the same structure and set of commands as machine languages. ",
"works in spurts and must insert a start bit before each data character and a stop bit at its termination to inform the receiver where it begins and ends.The term asynchronous is used to describe the process where transmitted data is encoded with start and stop bits, specifying the beginning and end of each character.",
"A method of data verification. A sends information to B. A keeps copy of message and B sends the message back when it has received it. If A doesn't hear from B then A sends it again after a reasonable amount of time.",
"Numbers that consist of the digits 0 and 1.",
"relating to or involving the application of statistical analysis to biological data.",
"Basic unit of computing",
"an image made up of a grid of colour values",
"A protocol that uses peer-to-peer file sharing",
"A bit map (often spelled 'bitmap') defines a display space and the color for each pixel or 'bit' in the display space. ",
"A data type that only has two values, true or false",
"Topology in a local area network (LAN) in which each node (workstation or other device) is connected to a main cable or link called the bus",
"a unit of digital information (usually 8 bits)",
"is the result of encryption performed on plaintext using an algorithm",
"Software or hardware that requests services from the server",
"When the code for the web page is processed on the users machine itself ",
"to write programming statements in a program",
"conversion of source code to machine readable form",
"The process of breaking down a problem into a series of logical steps.",
"Anything which can do what you ask it to do, without thinking about what it is doing",
"A group of computer systems that are linked through communication channels",
"This is the part of the CPU that controls the flow of instructions via a clock",
"Central proccessing unit -  Process all the instructions in the computer by doing basic arithmethics ",
"when a program stops working unexpectedly",
"Cascading Style Sheets. Used to stylize websites.",
"A collection of numbers or letters that are almost impossible to decipher without the correct interpretation tools",
"A collection of one or more related tables",
"A complex piece of software that manages a database",
"getting rid of mistakes in a program",
"break something down into smaller pieces",
"A set of smaller tasks that together make up one big task",
"erase characters from a text",
"The numbers we use in everyday life: digits between 0-9.",
"a denial-of-service (DoS) attack is an attempt to make a machine or network resource unavailable to its intended users, such as to temporarily or indefinitely interrupt or suspend services of a host connected to the Internet.",
"create computer programs",
"A device driver is a program that controls a particular type of device that is attached to your computer. ",
"a way of storing data using 1s and 0s",
"transferring a files from one device to another, usually through a website",
"to transform information in a way that makes it unreadable",
"Conversion of electronic data into a form which cannot be understood by unauthorized party",
"Data is put into numbers",
"Even parity refers to a parity checking mode in asynchronous communication systems in which an extra bit, called a parity bit, is set to one if there is an even number of one bits in a one-byte data item. If the number of one bits adds up to an odd number, the parity bit is set to zero.",
"Running a program or app",
"A group of characters that represent a single item of data in a file",
"stored data on suitable media",
"A firewall is a software program or piece of hardware that helps screen out hackers, viruses, and worms that try to reach your computer over the Internet.",
"A data type that is consisted of a decimal point number",
"A file transfer protocol used to transfer files from a host to clients over TCP based networks",
"A set of instructions similar to a procedure but with functions something is usually returned, possibly a string, value or other data type.",
"Image format capable for animation and can be losslessly-compressed",
"To gain unauthorized access to data in a system or computer.",
"The physical components that make up a computer system",
"The beginning of a WAV (RIFF) file, used to provide specifications on the file type.",
"Known as base-16 as well, consists of the digits between 0-9 and A-F",
"A computer that is connected to a computer network",
"Hypertext Markup Language. It is a Webpage file",
"The Hypertext Transfer Protocol (HTTP). HTTP is the foundation of data communication for the World Wide Web.",
"Feeding data or information into a device",
"can be between a human and a computer system",
"A global system of interconnected computer networks that use TCP/IP to link several billions of devices",
"An ISP Is a company that provides the user with access to the internet; they usually charge a monthly fee.",
"Many types of interupts but the main picture is for the interrupt to stop the CPU from processing all the instruction and handle the Input from the extrernal device such as a keyboard ",
" A signal that gets the attention of the CPU and is usually generated when I/O is required.",
"An internet protocol where each computer is uniquely identified in internet",
"IP adressing version 6 ",
"repeating something",
"an object oriented programming language",
"Bitmap based image format which utilizes lossy compression",
"Core of an OS, responsible for resource allocation, file management and security",
"Local area network - A network around the local area that connects machines together ",
"A library routine is a debugged block of code (subroutine, procedure, function etc), often designed to handle commonly occurring problems or tasks. Library routines are stored in a program library and given names. This allows them to be called into immediate use when needed, even from other programs.",
"The use and study of valid reasoning",
"Basic digital element for bulding a circuit, 1 is on and 0 is off",
"to enter username and access a system.",
"to continually repeat the processing of program statements.",
"A form of compression using algorhythms to reconstruct compressed data perfectly",
"Is the class of data encoding methods that uses inexact approximations and partial removal of data  to represent the content in a smaller file ",
"A MAC address is a unique number trhat identifies any device connected to the Internet. This address consists of the identity number of the device manufacturer (first 24 bits in groups of 3) and the serial number of the device (second 24 bits in groups of 3). The Mac address is very rarely changed so that a device can be identified no matter where it is.",
"Language which the machine can understand, direct downgrade from assembly language",
"is software designed to infiltrate or damage a computer system, without the owner's consent",
"internal storage area in a computer",
"create a representation of something",
"An output device used to display processed data.",
"Input device",
"A means of compressing a sound sequence into a very small file, to enable digital storage and transmission. (uses lossy compression)",
"The container file is used to identify and interleave different data types. Simpler container formats can contain different types of audio formats.",
"to browse and search for information",
"the information that you have on the internet about yourself",
"Operating system - s system software that manages computer hardware and software resources and provides common services for computer programs",
"receiving information or data after being processed",
"When each packet has it's own route and individually makes its way to the end destination  ",
"In computers, parallel processing is the processing of program instructions by dividing them among multiple processors with the objective of running a program in less time",
"check bit is a bit added to the end of a string of binary code that indicates whether the number of bits in the string with the value one is even or odd",
"a string of characters that allows access to a computer, interface, or system.",
"A network of computers configured to allow certain files and folders to be shared with everyone or with selected users.",
"s a form of online fraud very similar to phishing as pharmers rely upon the same bogus websites and theft of confidential information.",
"is an e-mail fraud method in which the perpetrator sends out legitimate-looking email in an attempt to gather personal and financial information from recipients. Typically, the messages appear to come from well known and trustworthy Web sites.",
"Hypertext Preprocessor. Adds interactivity to websites. A web programming language similar to Javascript",
"A minute area of illumination on a display screen, one of many from which an image is composed.",
"text that is not computationally tagged, specially formatted, or written in code.",
"Losslessly compressed image format used as a replacement for GIF",
"Points to a location in the memory ",
"A client/server protocol in which e-mails are received and held for you by your Internet server.",
"A key in a relational database that is unique for each record",
"Programs within programs created to carry out a specific task",
"a program that is being run on a computer",
"the ‘brain’ of the computer that does all the calculations",
"create a set of instructions to make a computer do someth",
"A way of writing instructions for the computer to execute",
"progressive encoding A method of image encoding that uses multiple scans rather than a single scan.",
"A set of rules or procedures for transmistting data between electronic devices",
"is a server (a computer system or an application) that acts as an intermediary for requests from clients seeking resources from other servers.",
"A high level programming language that has wide use and general purpose",
"A simple way to do a search in a Database",
"Random acces memory - Computer storage memory which is volatile. It allows recent application data to be saved while being  used for speed ",
"When disc is read and written to anywhere on the file ",
"The data stored for s number of fields in a single entry ",
"A register is an internal memory location within the CPU",
"Identified by the width and height of the imageas well as the total number of pixels in the image.",
"Read only memory - Computer hardware that stores programs or data that cannot be added to, modified, or deleted",
"a device that forwards data packets along networks. It is usually connected to more than one network ",
"The number of times an analog signal is measured (sampled) per second.",
"Determines how many gradations of amplitude can be represented in the digital waveform",
"a visual programming language where you use blocks to create software",
"move a page up or down",
"find something using a computer, often using a search engine",
"Non volatile memory used to store data that needs to be kept when the power is off",
"The pathway through a program determined by conditions",
"one thing after another",
"Instruction executed one after the other",
"CPUs which perform backend tasks, such as controlling printers, managing information, running databases and so on",
"A technique used in web development which involves employing scripts on a web server which produce a response customised for each client's request",
"A Simple Mail Transfer Protocol is a protocol used for email transfer",
"collection of data and instructions to enable a computer to perform a set of activities",
"A type of Malware that locates and saves data from users secretly.",
"Secure socket layer - technology is a standard for encrypted client/server network connections. Ussually used in web shopping",
"Topology in a local area network (LAN) in which all nodes (workstations or other devices) are directly connected to a common central computer. ",
"a sentence in a programming language",
"A data type that is consisted of a sequence of characters",
"An XML-based vector image format for two-dimensional graphics with support for interactivity and animation.",
"is an algorithm for cryptography that uses the same cryptographic key to encrypt and decrypt the message.",
"is a data transfer method in which a continuous stream of data signals is accompanied by timing signals (generated by an electronic clock) to ensure that the transmitter and the receiver are in step (synchronized) with one another.",
"Utility software is system software designed to help analyze, configure, optimize or maintain a computer.",
"a way of making sure that things work the way they are supposed to",
"Schematic description of the arrangement of a network, including its nodes and connecting lines",
"A file sent via bit torrent from peer to peer.",
"the transmission of a file to the internet",
"A user account is a collection of information that tells Windows which files and folders you can access, what changes you can make to the computer, and your personal preferences, such as your desktop background or screen saver.",
"Everything designed into an information device which a human being may interact with.",
"is an automatic computer check to ensure that the data entered is sensible and reasonable. It does not check the accuracy of data.",
"something that changes whilst a program is running",
"Created in graphic packages and are scalable.",
"is performed to ensure that the data entered exactly matches the original source.",
"attaches itself to a program or file enabling it to spread from one computer to another, leaving infections as it travels. Like a human virus, a computer virus can range in severity: some may cause only mildly annoying effects while others can damage your hardware, software or files. ",
"Model that includes, Input, Control unit, Arithmetic Logic Unit, memory and output",
"A type of sound file. A multi-format file that contains a header and data.",
"Software which allows the user to display a web page on the computer screen; this software interprets/translates the HTML from the website and shows the result.",
"A way of compiling files using lossless compression. Any file can be compressed into one of these archives."]

#Start your code here:

print(wordlist)
print(descriptions)
